require "forwardable"
require "latinverb_irregular_infinitives_retriever"

require "latinverb_imperatives/version"
require "latinverb_imperatives/imperatives_factory/imperatives_handler"
require "latinverb_imperatives/imperatives_factory/deponent_imperatives_handler"
require "latinverb_imperatives/imperatives_factory"
